### ISSUE TITLE
Windows Defender flags 1.2.0 exe

### ISSUE THREAD

**Issue by rlsolomon** [afit/wlan10#11]
Windows Defender flags the 1.2.0 exe as unsafe

**Comment by afit** [comment]
Interesting. Can you share a screenshot of its warning? I'd guess this is because the binary isn't signed, but the older builds also weren't signed. 🧐

**Comment by rlsolomon** [comment]
![image](https://user-images.githubusercontent.com/45888972/107073386-8d6d9a80-67a4-11eb-9cd1-288dd62ccf04.png)

![image](https://user-images.githubusercontent.com/45888972/107073609-d0c80900-67a4-11eb-809c-b5e1b8b5d83c.png)

Seems pretty non-specific...

**Comment by rlsolomon** [comment]
![image](https://user-images.githubusercontent.com/45888972/107074024-5ea3f400-67a5-11eb-9190-c2dba89fc128.png)

**Comment by afit** [comment]
Brilliant, thank you —  that's really helpful!

**Comment by afit** [comment]
Tried this on a new box; looks like this is now resolved. Please reopen otherwise. 👍
