### ISSUE TITLE
1.2.0 exe complains of missing .NET

### ISSUE THREAD

**Issue by rlsolomon** [afit/wlan10#12]
1.1.2 ran fine
1.2.0 complains .NET is missing and wants to download it

Running .NET 40 installer from Microsoft shows it's already installed (Win 10 20H2) as confirmed by control panel
![image](https://user-images.githubusercontent.com/45888972/107067321-58f5e080-679c-11eb-9afd-2b28cff9fe47.png)

**Comment by afit** [comment]
Thank you. That's not good. I built it with .NET 5 which may have been too ambitious. If you install the [.NET Desktop Runtime 5.0.2](https://dotnet.microsoft.com/download/dotnet/5.0) does that make it work?

**Comment by rlsolomon** [comment]
No joy...
![image](https://user-images.githubusercontent.com/45888972/107074494-0d483480-67a6-11eb-899f-40271d43f8df.png)


![image](https://user-images.githubusercontent.com/45888972/107074571-27821280-67a6-11eb-96c8-433db976f0b0.png)

ETA: I believe the readme calls out Net 4.0 so you might want to update that also.

**Comment by afit** [comment]
Thank you. Does 1.2.1 work if you expand the zip and everything in it before running the exe?

**Comment by rlsolomon** [comment]
Same results :(
![image](https://user-images.githubusercontent.com/45888972/107082725-db3ccf80-67b1-11eb-8c0b-91a59ded47b2.png)

**Comment by afit** [comment]
Thanks. I'll spin up a test machine so I can fix this without the back and forth!

**Comment by afit** [comment]
Does [this](https://github.com/afit/wlan10/files/5936997/wlan10-1.2.2.zip) work for you if you unzip it and run `setup.exe`? It should!

**Comment by rlsolomon** [comment]
YES! You've got it!

Just the EXE from the ZIP works as well now even without running Setup.

Awesome, thank you!

**Comment by afit** [comment]
That's great! Thank you so much. I've rereleased this as [1.2.1](https://github.com/afit/wlan10/releases/tag/1.2.1).
