### ISSUE TITLE
How to "start the app"???

### ISSUE THREAD

**Issue by ggonmar** [afit/wlan10#2]
Probably a totally rookie question, but... 
I've downloaded the project and I find no exe around to actually execute the app! 😟

**Comment by afit** [comment]
Hey — I've not rolled a release of the new changes yet, but I plan to in the near future. If you're technical, you could build it with Visual Studio.

In the meantime, the [last stable build is here](https://github.com/Bertware/wlan10/releases/tag/1.1.2).

**Comment by ggonmar** [comment]
Sublime, thank you!

**Comment by rlsolomon** [comment]
> I've downloaded the project and I find no exe around to actually execute the app! 😟

Just another user who came by looking for a released EXE file and eventually found the previous maintainer's EXE.  Would love to have one here - great tool!

**Comment by afit** [comment]
Thank you! I've just added the older releases here. Will be posting a new build soon. 👍
